config:
  git_user_name: CircleCI
  git_user_email: circleci@cureapp.jp
  npm_update_depth: 1
  version_prefix: v
  create_branch: false
  npm_shrinkwrap: false
  create_gh_pages: false
  gh_pages_dir: null
circle: {}
